### ISSUE TITLE
Educate the customer about the widgets zone in the upper right and provide recommendation for only 1 widget

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#12]
Per Chris

**Comment by angela-crist** [comment]
Limiting the header widget to one item
    ⁃ Educate customers this space is only for one

**Comment by garand** [comment]
Let's start by making a note to educate customers and we can explore adding a limit to this area later. It's not something that is easily added.

**Comment by angela-crist** [comment]
I have added this to my list of documentation to create.  I will close out this issue as I will be crossing off my documentation list as I create it.  

For reference:  documentation list lives here: https://docs.google.com/document/d/1VpHNjogk_-LupOyystOadlyPDAVWcHW5_i4WYbZqgb4/edit#
