### ISSUE TITLE
Need a way for the header to go over the top of the content 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#18]
We need to decide if this is per theme or if this is a global thing - Ask Chris for Details 

'Note taking from this agenda on 7/8: https://docs.google.com/document/d/1toiiDqqawwh1_2xZlzUOhQe89Rw4kzSZYz3JWQ3AWyA/edit#'

**Comment by garand** [comment]
@angela-crist Can you describe what this is a little more?

**Comment by angela-crist** [comment]
@chriswallace Can you provide insight on what you would like to see here?

**Comment by angela-crist** [comment]
For Praise not sure how we want to do that so for now we will close but for more modern theme we can bring this back up - Per Chris
