### ISSUE TITLE
Choose the full width template with 1 column full layout is broken

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#19]
http://lift.d.pr/ZzUS/12Xtw1Vv

**Comment by garand** [comment]
@chriswallace Can you elaborate on this?

**Comment by angela-crist** [comment]
<img width="931" alt="screen shot 2015-07-08 at 4 53 40 pm" src="https://cloud.githubusercontent.com/assets/7047954/8581990/1576934c-2592-11e5-90ca-3dc9d1eb2c17.png">

**Comment by garand** [comment]
This is fixed with [this commit](https://github.com/faithmade/rock/commit/7513beeda8b51823582e6f8a09c0ff270462ae64).
