### ISSUE TITLE
Add image of what layout would look like next to layout option 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#20]
http://lift.d.pr/90fP/1yZueQSf

**Comment by angela-crist** [comment]
@garand Just want to remind you of your idea in today's meeting about selecting the grid and the layout is highlighted 

Lower priority

**Comment by garand** [comment]
Fixed with [this commit](https://github.com/faithmade/rock/commit/5b16432bdcea67cc6fb2ed8743127ab93637a70e).
