### ISSUE TITLE
Page width needs to be 75%

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#24]
Brad was playing around and was able to make the grid look better by doing this and keeping it responsive

http://lift.d.pr/1iK5D/16S5Os0T - Values Before

<img width="533" alt="screen shot 2015-07-08 at 3 44 57 pm" src="https://cloud.githubusercontent.com/assets/7047954/8580377/5e9b7c72-2588-11e5-8991-a69212fa945d.png">

http://lift.d.pr/ACgW/5DAg1WAP - Values After

**Comment by garand** [comment]
This is due to the widget area not having a widget in it.

This will be fixed with #26.
