### ISSUE TITLE
Build a homepage by using Faith builder that can match the original design for 360

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#29]
We discussed this in the 7/30 Status meeting.  James is complete so @garand I will assign to you. 

This originated here: #17

**Comment by angela-crist** [comment]
Original design is here: https://liftux.slack.com/archives/faithmade/p1438809542000070

**Comment by angela-crist** [comment]
Brad offered if he could help with anything and this is one thing I saw :) Enjoy @imbradmiller Let me know if you need anything. Click on the link above to get the original PSD.

**Comment by imbradmiller** [comment]
I was trying to do this task this evening but ran into a few hiccups. The site was really slow first off and then the PSD only has one single page design. Which is just the about us page with a sidebar. So I have a few questions about this and if it's that simple, I'll have this done tomorrow for sure. :+1:

**Comment by angela-crist** [comment]
Here's the link to the PSD's : https://liftux.slack.com/archives/faithmade/p1439217764000013

Create in http://layouts.faithmade.com/ (you can change the theme to Praise)

Use the design as a guideline, it doesn't have to be those specific modules.

**Comment by imbradmiller** [comment]
I have completed what I can based off the PSD. Please review and let me know if there is anything else you need me to do.

**Comment by garand** [comment]
@imbradmiller Can you include the link to that template here?

**Comment by angela-crist** [comment]
Here you go @garand 
https://layouts.faithmade.com/home/
https://layouts.faithmade.com/wp-admin/post.php?post=24&action=edit

Is this what you need?

**Comment by garand** [comment]
Yea, thanks.

**Comment by angela-crist** [comment]
@chriswallace This is the issue that Brad completed creating the homepage layout for Praise.
https://layouts.faithmade.com/home/

I'll assign to you now to include in your layout consistency issues here: https://github.com/LiftUX/faithmade/labels/layouts

**Comment by angela-crist** [comment]
This issue is complete what remains is creating a consistent look that is this issue: https://github.com/LiftUX/faithmade/issues/29 so I will close this issue out. :) yes!!
