### ISSUE TITLE
Will users be able to change the color of the giving button with colorcase?

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#4]
<img width="397" alt="screen shot 2015-07-06 at 4 44 44 pm" src="https://cloud.githubusercontent.com/assets/7047954/8532743/6071b678-23fe-11e5-953b-5c22f1c67447.png">

If for some reason they keep the header image and place the giving widget there it will look like this.

**Comment by garand** [comment]
![screen shot 2015-07-23 at 4 51 46 pm](https://cloud.githubusercontent.com/assets/82437/8861919/21b266fc-315b-11e5-96ca-0b428feae68e.png)
