### ISSUE TITLE
Background of widgets is too dark

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#5]
<img width="1207" alt="screen shot 2015-07-06 at 4 54 08 pm" src="https://cloud.githubusercontent.com/assets/7047954/8532937/a5649dc6-23ff-11e5-95cd-8dedf014d9dd.png">

**Comment by angela-crist** [comment]
From Chris: 
`Widget backgrounds are soo very dark. We need to lighten them up. Primary color box for the title and then a light gray for the background on the content of the widget will work fine.`

**Comment by garand** [comment]
![screen shot 2015-07-11 at 4 31 19 pm](https://cloud.githubusercontent.com/assets/82437/8635270/4a3e73f6-27ea-11e5-8f74-f87817cfef10.png)
