### ISSUE TITLE
The widget colors look harsh with the colors we are currently using 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/praise#7]
<img width="303" alt="screen shot 2015-07-06 at 4 56 18 pm" src="https://cloud.githubusercontent.com/assets/7047954/8533003/fbe28e7e-23ff-11e5-8d49-653d6adfdab9.png">

**Comment by garand** [comment]
Completed with [this commit](https://github.com/faithmade/praise/commit/9b81a1f27b7028239e7de7f3e6fb9490c3295561).

![screen shot 2015-07-11 at 4 31 19 pm](https://cloud.githubusercontent.com/assets/82437/8635270/4a3e73f6-27ea-11e5-8f74-f87817cfef10.png)
