### ISSUE TITLE
The page template isn't aligning correctly when using Faithbuilder and full width template

### ISSUE THREAD

**Issue by imbradmiller** [faithmade/praise#9]
The page template isn't aligning correctly when using Faithbuilder and full width template. If you have full width template set and content entered with Faithbuilder, it bust out of the container.  Like so. http://lift.d.pr/19LYK/2QI56aVC

**Comment by garand** [comment]
This is fixed with [this commit](https://github.com/faithmade/rock/commit/7513beeda8b51823582e6f8a09c0ff270462ae64).
